### ISSUE TITLE
Remove `unless` from the list

### ISSUE THREAD

**Issue by andreasabel** [NorfairKing/haskell-dangerous-functions#20]
Great list!

But I think `unless` does not deserve to be on this list.  
It isn't confusing and it make things _clearer_ when checking assertions.  Say you want to assert `n > 0`, then I suggest a formulation like this:
```haskell
  ... something producing n...
  unless (n > 0) $ do
    debugPrint "assertion n > 0 violated"...
    throwError Impossible
```

https://github.com/NorfairKing/haskell-dangerous-functions/blob/f511f1baa37b2a87fc231421b32601846e995192/README.md?plain=1#L690-L699

**Comment by NorfairKing** [comment]
All you're claiming here is that you're so much less prone to error that you can afford not to type `not $`.
This is a list of functions that you can warn against by default, feel free to omit any of the ones that you don't think are relevant for you.
But it's important to realise that these functions are here because they've already caused production outages, not because I think that Haskellers are stupid.

**Comment by andreasabel** [comment]
> All you're claiming here is that you're so much less prone to error that you can afford not to type `not $`.

Piano, piano...

I'd say I am very prone to error when it comes to negation.  This is why any `not` that I can save makes me more confident in my reasoning... :D

We are all stupid, more or less... :D
