### ISSUE TITLE
fromIntegral consistency

### ISSUE THREAD

**Issue by brprice** [NorfairKing/haskell-dangerous-functions#24]
`fromIntegral` is forbidden: https://github.com/NorfairKing/haskell-dangerous-functions/blob/6133eac8e89ea140269d9196dd8018631f44efdb/hlint.yaml#L111-L114, but also recommended: https://github.com/NorfairKing/haskell-dangerous-functions/blob/6133eac8e89ea140269d9196dd8018631f44efdb/hlint.yaml#L31 (also, typo)

Since `fromIntegral` is forbidden, should we also forbid `fromInteger`, as it has the same problems?

**Comment by NorfairKing** [comment]
@brprice This is a good point!

1. The `genericLength` issue is really sad because there's no good alternative so far. I'm not sure what to recommend. I'd be happy if we removed the `fromIntegral` recommendation but not sure what to use instead.
2. I agree that `fromInteger` should be forbidden as well.

PR welcome.

**Comment by brprice** [comment]
> @brprice This is a good point!
> 
>     1. The `genericLength` issue is really sad because there's no good alternative so far. I'm not sure what to recommend. I'd be happy if we removed the `fromIntegral` recommendation but not sure what to use instead.

Agree -- I'm not sure how to do better than just removing the recommendation.

>     2. I agree that `fromInteger` should be forbidden as well.
> PR welcome.

I opened #25
